Golden Globe API
Technigo/project-express-api pull request #109
Opened 2020-12-13 09:05 UTC by Snabbina

2021-01-08 13:13 UTC, EmOlsz requested changes

2021-01-08 13:13 UTC, EmOlsz commented on server.js
> +console.log(data.length)
Let's delete this console.log

2021-01-08 13:13 UTC, EmOlsz commented on server.js
> +  res.send('Welcome to the Golden Globe API of nominations for 2010-2019')
Would be better to send it as an object :

```
res.json({ message: 'Welcome to the Golden Globe API of nominations for 2010-2019' })
```

2021-01-08 13:13 UTC, EmOlsz commented on server.js
> +  console.log(showWon)
Another console.log

2021-01-19 14:48 UTC, Snabbina commented
Hey hey, @EmOlsz made some nice changes to the code, please let me know if it is ok now =) /Sabina

2021-01-19 15:55 UTC, EmOlsz commented
Hey Sabina, thanks for fixes, project is now approved :)

2021-01-19 15:55 UTC, EmOlsz approved these changes

2021-03-09 13:20 UTC, closed without merging