Express Nathalie Nordström
Technigo/project-express-api pull request #115
Opened 2020-12-13 14:45 UTC by nathalienordstrom

2021-01-12 16:34 UTC, HIPPIEKICK requested changes
From the requirements:
- A minimum of one endpoint to return a single result (single element).

Create an endpoint that returns a single element (e.g. using ID), and change so that your API has RESTful naming (a noun in plural is a good rule of thumb)

2021-01-12 16:34 UTC, HIPPIEKICK commented on server.js
> +app.get('/year', (req, res) => {
Endpoints should be named after what they return so this could be named `shows` or `/titles` or similar

2021-01-12 16:34 UTC, HIPPIEKICK commented on server.js
> +})
Nice with some filtering 👍 
A suggestion would be to make this a query param under your first endpoint, like:
`/shows?year=2020`

2021-02-10 12:33 UTC, HIPPIEKICK requested changes
Nice job Nathalie! Just remove the commented out code and update your readme with the new deploy 👍

2021-03-09 13:23 UTC, EmOlsz approved these changes

2021-03-09 13:24 UTC, closed without merging