Hannah, Project API
Technigo/project-express-api pull request #150
Opened 2021-05-07 13:19 UTC by jesinkey

2021-05-16 20:39 UTC, KarolCislowski requested changes
Please send a Heroku link for testing 🤓

2021-05-16 20:39 UTC, KarolCislowski commented on server.js
> -//   PORT=9000 npm start
Nice cleaning 🧹

2021-05-16 20:39 UTC, KarolCislowski commented on server.js
> +  }
nice filtering 👍🏻

2021-05-17 06:50 UTC, jesinkey commented
Sorry! https://express-api-hannahj.herokuapp.com/

2021-05-25 07:24 UTC, KarolCislowski approved these changes
Great API 👍🏻

2022-04-21 13:45 UTC, closed without merging