Project Express-API Maria Sparre
Technigo/project-express-api pull request #182
Opened 2021-05-09 20:26 UTC by MarySparrow

https://netflixmovies.herokuapp.com/movies

2021-05-16 10:20 UTC, KarolCislowski requested changes
Please change your endpoints to meet REST convention 🤓

2021-05-16 10:20 UTC, KarolCislowski commented on server.js
> +app.get('/id/:id', (request, response) => {
REST naming convention is to provide the name of the list you are filtering, so here you should use `/movies/:id` 
When you filtering by the primary key (id here) you do not specify the key, so `/movies/id/:id` would be wrong as well.

2021-05-16 10:20 UTC, KarolCislowski commented on server.js
> +app.get('/year/:year', (request, response) => {
Again you are filtering movies so it should be `/movies/years/:year`

2021-05-16 10:20 UTC, KarolCislowski commented on server.js
> +app.get('/type/type', (request, response) => {
and remember that you need to use plural forms in your endpoints `/movies/types/:type`

2021-05-16 10:20 UTC, KarolCislowski commented on server.js
> +  response.json({ length: data.length, data: data})
nice filtering

2021-05-17 12:33 UTC, MarySparrow commented
Hello Karol,

Thanks for clarifying REST convention :)

One part I am not sure if I have mistaken still, (see snippet below)  you
write /movies/types/:type but will it also work typing /movies/types/type
with the filtering I have set up ?

Little confused in the learning here still.

Thanks!
Maria

server.js
<https://github.com/Technigo/project-express-api/pull/182#discussion_r633072889>
:

>  })

+//return type of movies, filtered out to not show duplicates

+app.get('/type/type', (request, response) => {


and remember that you need to use plural forms in your endpoints
/movies/types/:type
------------------------------


Den sön 16 maj 2021 kl 12:20 skrev Karol Cislowski ***@***.***
>:

> *@KarolCislowski* requested changes on this pull request.
>
> Please change your endpoints to meet REST convention 🤓
> ------------------------------
>
> In server.js
> <https://github.com/Technigo/project-express-api/pull/182#discussion_r633072681>
> :
>
> >
>
> -// Start defining your routes here
>
> -app.get('/', (req, res) => {
>
> -  res.send('Hello world')
>
> +// Start route
>
> +app.get('/', (request, response) => {
>
> +  response.send(listEndpoints(app))
>
> +})
>
> +// return all movies
>
> +app.get('/movies', (request, response) => {
>
> +  response.json(movies)
>
> +})
>
> +//return one single movie based on known ID
>
> +app.get('/id/:id', (request, response) => {
>
>
> REST naming convention is to provide the name of the list you are
> filtering, so here you should use /movies/:id
> When you filtering by the primary key (id here) you do not specify the
> key, so /movies/id/:id would be wrong as well.
> ------------------------------
>
> In server.js
> <https://github.com/Technigo/project-express-api/pull/182#discussion_r633072750>
> :
>
> > +  response.send(listEndpoints(app))
>
> +})
>
> +// return all movies
>
> +app.get('/movies', (request, response) => {
>
> +  response.json(movies)
>
> +})
>
> +//return one single movie based on known ID
>
> +app.get('/id/:id', (request, response) => {
>
> +  const { id } = request.params
>
> +  const filteredMovies = movies
>
> +    .find(movie => movie.show_id === +id
>
> +  )
>
> +filteredMovies ? response.json(filteredMovies) : response.status(404).send(`There is no movie with ID "${id}" in the system`)
>
> +})
>
> +//return movie based on year of release
>
> +app.get('/year/:year', (request, response) => {
>
>
> Again you are filtering movies so it should be /movies/years/:year
> ------------------------------
>
> In server.js
> <https://github.com/Technigo/project-express-api/pull/182#discussion_r633072889>
> :
>
> >  })
>
> +//return type of movies, filtered out to not show duplicates
>
> +app.get('/type/type', (request, response) => {
>
>
> and remember that you need to use plural forms in your endpoints
> /movies/types/:type
> ------------------------------
>
> In server.js
> <https://github.com/Technigo/project-express-api/pull/182#discussion_r633072908>
> :
>
> > +  if(director){
>
> +    data = data
>
> +      .filter(item => item.director.toLowerCase().includes(director.toLowerCase()))
>
> +  }
>
> +  if(country) {
>
> +    data = data
>
> +      .filter(item => item.country.toLowerCase().includes(country.toLowerCase()))
>
> +  }
>
> +  if(title){
>
> +    data = data
>
> +      .filter(item => item.title.toString().toLowerCase().includes(title.toLowerCase()))
>
> +  }
>
> +  response.json({ length: data.length, data: data})
>
>
> nice filtering
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-express-api/pull/182#pullrequestreview-660424512>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIS6AHMCMBXGS5MF2DKHOW3TN6L67ANCNFSM44PSWTQQ>
> .
>

2021-05-25 07:17 UTC, KarolCislowski approved these changes
Nice app 👍🏻

2021-12-06 08:59 UTC, closed without merging