Express-API-Elaine
Technigo/project-express-api pull request #190
Opened 2021-05-09 21:37 UTC by CoffeeDoodles

2021-05-16 09:30 UTC, KarolCislowski requested changes
please provide a Heroku link for testing.

2021-05-16 09:55 UTC, CoffeeDoodles commented
@KarolCislowski  Ah! Sorry about that I thought I had pushed the last update but... apparently I hadn't, it is now there in the README.

2021-05-25 07:20 UTC, KarolCislowski approved these changes
Nice API 👍🏻

2021-05-25 07:20 UTC, KarolCislowski commented on README.md
Short documentation would be nice 🤓

2021-05-25 07:20 UTC, KarolCislowski commented on server.js
> +
Nice filtering 👍🏻

2021-12-06 08:59 UTC, closed without merging