Express Api - Malin Göthe
Technigo/project-express-api pull request #194
Opened 2021-05-10 15:10 UTC by M4L5

2021-05-16 08:49 UTC, KarolCislowski requested changes
Please add Heroku link for testing 🤓

2021-05-16 14:20 UTC, M4L5 commented
Hi Karol! Here is the Heroku link: https://goethe-express-deployment.herokuapp.com/avocados

2021-05-25 07:21 UTC, KarolCislowski approved these changes
Nice API 👍🏻

2021-05-25 07:21 UTC, KarolCislowski commented on README.md
> -Every project should be deployed somewhere. Be sure to include the link to the deployed project so that the viewer can click around and see what it's all about.
Short documentation would be nice 🤓

2021-05-25 07:21 UTC, KarolCislowski commented on server.js
> +})
Nice filtering 👍🏻

2021-12-06 08:59 UTC, closed without merging