Yifan-Avocado-Sales-API
Technigo/project-express-api pull request #480
Opened 2024-04-28 15:54 UTC by Yifan-858

## Netlify link
https://avocado-sales-knno.onrender.com

## Collaborators

2024-05-03 17:32 UTC, kathinka requested changes

2024-05-03 17:32 UTC, kathinka commented on README.md
Hi Yifan, 

How nice to review such a clean project! 

You have almost done all of the requirements for this project.

- Your API should have at least 3 routes. Try to push yourself to do more, though!✅
  - The endpoint "/" should return documentation of your API using e.g. [Express List Endpoints](https://www.npmjs.com/package/express-list-endpoints)✅
  - A minimum of one endpoint to return a **collection** of results (array of elements).✅
  - A minimum of one endpoint to return a **single** result (single element).❌
- Your API should be [RESTful](https://www.notion.so/23473abe980e40aaa932914751055d22?pvs=21).

So i guess you just have to toss in an endpoint to search on id and you are all good for this weeks assignement 👏🏼

2024-05-03 17:38 UTC, Yifan-858 commented
Hey Kathinka, Thank you for the reminder! It totally skipped my mind :P

2024-05-06 08:30 UTC, AntonellaMorittu approved these changes
Hi Yifan, well done completing your first API! 👏 
Your code indeed meets the specified requirements, nice! 😎 One small suggestion is to organize the endpoints in a more logical order. Typically, endpoints should be ordered from more general to more specific. For example, "/avocado-sales" could be defined before "/avocado-sales/region/:regionName" endpoints. This is to ensure that more specific routes are not shadowed by more general ones.

Other than that, the code looks good! Keep it up 💯

2024-12-09 10:08 UTC, closed without merging