Wen's API Service
Technigo/project-express-api pull request #482
Opened 2024-04-29 15:21 UTC by wwenzz

## Netlify link
https://wen-api-service.onrender.com/

## Collaborators
[wwenzz]

2024-05-06 08:52 UTC, AntonellaMorittu requested changes
Hello Wen, well done completing your first API! 👏 Your code meets almost all the requirements, I am curious how did you end up adding an `index.ejs` file to list your endpoints? Using `expressListEndpoints` will take care of it, see the [example](https://express-demo-bu5u.onrender.com/) provided for this week's assignment. You want to get a list of clickable endpoints with this readable format. Please fix that and you're good to go 🚀

2024-05-06 09:18 UTC, AntonellaMorittu approved these changes

2024-05-07 08:05 UTC, almaherris reviewed
Clean code with nice simple frontend to your API instructions. Good job as always Wen 🤩

2024-05-07 08:05 UTC, almaherris commented on server.js
> +    );
Good that you're handling unavailable requests and I like that you are suggesting to the user how to do it correctly! Very user friendly 👍

2024-05-07 08:05 UTC, almaherris commented on server.js
> +// songs endpoint: display all songs and filter songs based on genre and/or artist
All your endpoints seem to be working well, and the code looks clean!

2024-12-09 10:08 UTC, closed without merging