express api
Technigo/project-express-api pull request #494
Opened 2024-05-03 12:12 UTC by Josephineoderland

## Netlify link
https://master--reliable-kleicha-adc2e5.netlify.app

2024-05-07 09:23 UTC, AntonellaMorittu commented
Hi Josephine, please add the link to your deployed API in the readme or in the PR template :)

2024-05-07 12:20 UTC, AntonellaMorittu requested changes
Please add the link to your deployed api 👍

2024-05-12 19:54 UTC, viktoria-olo reviewed
Great use of endpoints and sorting. Very good error handling. Also nice that you did a frontend part. Well done!

2024-05-12 19:54 UTC, viktoria-olo commented on backend/routes/api.js
> +            ? `http://localhost:3000/sales?page=${page + 1}&limit=${limit}`
The localhost url should probably be updated to the deployed render address.

2024-05-12 19:54 UTC, viktoria-olo commented on backend/routes/api.js
> +            details: "Please provide a valid ID. Example: /sales/1",
Very nice and clear error handling! Same for status 404 below.

2024-05-17 09:37 UTC, AntonellaMorittu approved these changes

2024-12-09 10:08 UTC, closed without merging