Mai Expressjs api Week 13
Technigo/project-express-api pull request #502
Opened 2024-05-04 06:37 UTC by maikanetaka

## Netlify link
https://mai-express-api.onrender.com/

2024-05-07 13:02 UTC, AntonellaMorittu requested changes
Hello Mai, well done completing your first API! It meets almost all the main requirements, make sure the  `/netflix-titles/:id` endpoints will work to pass. I left some comments in the code for you to read and improve ⭐ ciao! 👋

2024-05-07 13:02 UTC, AntonellaMorittu commented on server.js
> +});
if your endpoint accepts some queries to filter the data, it's good to inform the user and add it to the documentation. You could do something like this:

```javascript
app.get("/", (req, res) => {
  const endpoints = expressListEndpoints(app);
  const updatedEndpoints = endpoints.map((endpoint) => {
    if (endpoint.path === '/netflix-titles') {
      endpoint.query = ['release_year']; // Add the release_year query parameter
    }
    return endpoint;
  });
  res.json(updatedEndpoints);
});
```

2024-05-19 19:30 UTC, maikanetaka commented on server.js
> +  const id = req.params.id;
Thank you for pointing out! I have fixed by adding parseInt and seems working!

2024-05-21 12:51 UTC, HIPPIEKICK approved these changes

2024-12-09 10:08 UTC, closed without merging