NetflixData Api
Technigo/project-express-api pull request #94
Opened 2020-12-11 14:10 UTC by moablomkvist

2021-01-05 15:49 UTC, EmOlsz requested changes

2021-01-14 15:42 UTC, moablomkvist commented on server.js
> +app.get('c', (req, res) => {
A mistake that the letters fell out when I copy / paste in the last commit. I've fixed it now.

2021-01-14 15:43 UTC, moablomkvist commented on server.js
> +  const directorsArray = directorsOfProductions.filter(item => item);
But is it wrong to use filters if the purpose was to filter out those that are not empty. Does it work with map as well?

2021-01-14 17:16 UTC, EmOlsz commented on server.js
> +  const directorsArray = directorsOfProductions.filter(item => item);
Ahhh, sorry, my bad. I assumed that every element inside `directorsOfProductions` is non empty.
It's ok as it is then :)

2021-01-18 09:11 UTC, EmOlsz approved these changes

2021-03-09 13:21 UTC, closed without merging